openapi: 3.0.0
info:
  title: Todo List API
  description: API para gerenciar uma lista de tarefas simples
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Servidor de desenvolvimento

paths:
  /tasks:
    post:
      summary: Adicionar uma nova tarefa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                responsible:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Tarefa adicionada com sucesso
        '400':
          description: Requisição inválida

  /tasks/pending:
    get:
      summary: Obter todas as tarefas pendentes
      responses:
        '200':
          description: Lista de tarefas pendentes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

  /tasks/completed:
    get:
      summary: Obter todas as tarefas concluídas
      responses:
        '200':
          description: Lista de tarefas concluídas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

  /tasks/{id}/complete:
    put:
      summary: Marcar uma tarefa como concluída
      parameters:
        - name: id
          in: path
          required: true
          description: ID da tarefa a ser marcada como concluída
          schema:
            type: integer
      responses:
        '200':
          description: Tarefa marcada como concluída com sucesso
        '400':
          description: Requisição inválida
        '404':
          description: Tarefa não encontrada

  /tasks/{id}/revert:
    put:
      summary: Reverter uma tarefa concluída para pendente
      parameters:
        - name: id
          in: path
          required: true
          description: ID da tarefa a ser revertida
          schema:
            type: integer
      responses:
        '200':
          description: Tarefa revertida com sucesso
        '400':
          description: Requisição inválida
        '404':
          description: Tarefa não encontrada

  /tasks/{id}:
    delete:
      summary: Excluir uma tarefa
      parameters:
        - name: id
          in: path
          required: true
          description: ID da tarefa a ser excluída
          schema:
            type: integer
      responses:
        '200':
          description: Tarefa excluída com sucesso
        '400':
          description: Requisição inválida
        '404':
          description: Tarefa não encontrada

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        description:
          type: string
        responsible:
          type: string
        email:
          type: string
        completed:
          type: boolean
